# Generated by Django 5.2.1 on 2026-03-14 12:59

import django.db.models.deletion
import django.utils.timezone
import emr.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_dicom', models.FileField(upload_to=emr.models._dicom_upload_path)),
                ('preview_png', models.ImageField(blank=True, null=True, upload_to=emr.models._preview_upload_path)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('download_medicalimage', 'Can download original medical image')],
            },
        ),
        migrations.CreateModel(
            name='DicomMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(blank=True, max_length=32)),
                ('study_instance_uid', models.CharField(blank=True, max_length=128)),
                ('series_instance_uid', models.CharField(blank=True, max_length=128)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=128)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('columns', models.IntegerField(blank=True, null=True)),
                ('bits_allocated', models.IntegerField(blank=True, null=True)),
                ('photometric_interpretation', models.CharField(blank=True, max_length=64)),
                ('extracted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dicom', to='emr.medicalimage')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_team', models.ManyToManyField(blank=True, related_name='care_team_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('primary_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('download_medicalrecord', 'Can download medical record exports')],
            },
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='emr.medicalrecord'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', 'created_at'], name='emr_medical_patient_59a09e_idx'),
        ),
    ]
