# Generated by Django 5.2.1 on 2026-04-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_additional_notes_appointment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='canceled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
